# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  pull-requests: 
    - step: Test 1
      script: echo Test 1 ✓
    - step: Test 2
      script: echo Test 2 ✓
