# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test: 
    name: Test Code
    runs-on: ubuntu-18.04
    steps:
      - name: Test 1
        run: echo "Test 1 Passed ✓"
      - name: Test 2
        run: echo "Test 2 Passed ✓"